# Includes complete Jenkins configuration in order to run croc-hunter pipeline
# To install on your own cluster, run:
# helm --namespace jenkins --name jenkins -f ./jenkins-values.yaml install stable/jenkins

Master:
  HostName: jenkins.muztagh.info

  Ingress:
    Annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod

    TLS:
      - secretName: jenkins.muztagh.info
        hosts:
          - jenkins.muztagh.info

Agent:
  Enabled: false

Persistence:
  Enabled: true
  StorageClass: "nfs"
